FROM wazuh/wazuh-manager:4.14.4

USER root

RUN mkdir -p /etc/ssl
RUN mkdir -p /wazuh-config-mount/etc

COPY config/wazuh_indexer_ssl_certs/root-ca-manager.pem /etc/ssl/root-ca.pem
COPY config/wazuh_indexer_ssl_certs/wazuh.manager.pem /etc/ssl/filebeat.pem
COPY config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem /etc/ssl/filebeat.key

COPY config/wazuh_cluster/wazuh_manager.conf /wazuh-config-mount/etc/ossec.conf

RUN chmod 640 /etc/ssl/root-ca.pem /etc/ssl/filebeat.pem /etc/ssl/filebeat.key /wazuh-config-mount/etc/ossec.conf || true
