FROM wazuh/wazuh-indexer:4.14.4

USER root

COPY config/wazuh_indexer_ssl_certs/root-ca.pem /usr/share/wazuh-indexer/config/certs/root-ca.pem
COPY config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem /usr/share/wazuh-indexer/config/certs/wazuh.indexer.key
COPY config/wazuh_indexer_ssl_certs/wazuh.indexer.pem /usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem
COPY config/wazuh_indexer_ssl_certs/admin.pem /usr/share/wazuh-indexer/config/certs/admin.pem
COPY config/wazuh_indexer_ssl_certs/admin-key.pem /usr/share/wazuh-indexer/config/certs/admin-key.pem

COPY config/wazuh_indexer/wazuh.indexer.yml /usr/share/wazuh-indexer/config/opensearch.yml
COPY config/wazuh_indexer/internal_users.yml /usr/share/wazuh-indexer/config/opensearch-security/internal_users.yml

RUN chown -R wazuh-indexer:wazuh-indexer /usr/share/wazuh-indexer/config && \
    find /usr/share/wazuh-indexer/config -type d -exec chmod 750 {} \; && \
    find /usr/share/wazuh-indexer/config -type f -exec chmod 640 {} \;
